### ISSUE TITLE
使用java8，开启jack编译

### ISSUE THREAD

**Issue by zengbobo0805** [netease-kit/nim-uikit-android#10]
# _******************application  build.gradle配置*********************************_
```
android {
    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 25
         ......
        //开启jack编译
        **jackOptions {
            enabled true
        }**
    }
      ......
    compileOptions {
        sourceCompatibility **JavaVersion.VERSION_1_8**
        targetCompatibility **JavaVersion.VERSION_1_8**
    }
}
```
# _********************报错**********************************_

```
> 06-29 17:16:08.157 21869-21869/com.netease.nim.demo E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                       Process: com.netease.nim.demo, PID: 21869
>                                                                       java.lang.IllegalAccessError: Illegal class access: 'com.netease.nimlib.sdk.NIMClient' attempting to access 'com.netease.nimlib.r.g' (declaration of 'com.netease.nimlib.sdk.NIMClient' appears in /data/app/com.netease.nim.demo-1/base.apk)
>                                                                           at com.netease.nimlib.sdk.NIMClient.init(Unknown Source)
>                                                                           at com.netease.nim.demo.NimApplication.onCreate(NimApplication.java:68)
>                                                                           at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
>                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
>                                                                           at android.app.ActivityThread.-wrap2(ActivityThread.java)
>                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
>                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                           at android.os.Looper.loop(Looper.java:154)
>                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119)
>                                                                           at java.lang.reflect.Method.invoke(Native Method)
>                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

# _# *****************************错误分析**********************************_
 
![qq 20170629173248](https://user-images.githubusercontent.com/6917259/27681220-0e747d28-5cf1-11e7-8735-69fe04e4b787.png)

**Comment by zengbobo0805** [comment]
这个要怎么改啊，为什么其他类文件不会有这个问题，这个类有什么特别吗？！
