### ISSUE TITLE
聊天界面长按消息会崩溃

### ISSUE THREAD

**Issue by WilliamsLee** [netease-kit/nim-uikit-android#43]
这是什么问题，就只是启动了一个单聊界面，可以收发消息，但是消息长按就崩溃

**Comment by FreeSunny** [comment]
> ，

日志有吗？

**Comment by cheng2290** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.netease.nim.uikit.business.session.module.MsgRevokeFilter.shouldIgnore(com.netease.nimlib.sdk.msg.model.IMMessage)' on a null object reference
        at com.netease.nim.uikit.business.session.module.list.MessageListPanelEx$MsgItemEventListener.enableRevokeButton(MessageListPanelEx.java:888)
        at com.netease.nim.uikit.business.session.module.list.MessageListPanelEx$MsgItemEventListener.prepareDialogItems(MessageListPanelEx.java:870)
        at com.netease.nim.uikit.business.session.module.list.MessageListPanelEx$MsgItemEventListener.onNormalLongClick(MessageListPanelEx.java:852)
        at com.netease.nim.uikit.business.session.module.list.MessageListPanelEx$MsgItemEventListener.showLongClickAction(MessageListPanelEx.java:839)
        at com.netease.nim.uikit.business.session.module.list.MessageListPanelEx$MsgItemEventListener.onViewHolderLongClick(MessageListPanelEx.java:788)
        at com.netease.nim.uikit.business.session.viewholder.MsgViewHolderBase$5.onLongClick(MsgViewHolderBase.java:325)
        at android.view.View.performLongClick(View.java:5254)

**Comment by cheng2290** [comment]
我也遇到了，上面是日志

**Comment by FreeSunny** [comment]
> 我也遇到了，上面是日志

NimUIKit.setMsgRevokeFilter 没有设置
