### ISSUE TITLE
Didn't find class "com.netease.nim.uikit.common.media.model.GenericFileProvider"

### ISSUE THREAD

**Issue by sunlinkun** [netease-kit/nim-uikit-android#46]
有的手机上不会报这个错，有的手机上报，这是什么原因啊？
java.lang.RuntimeException: Unable to get provider com.netease.nim.uikit.common.media.model.GenericFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.netease.nim.uikit.common.media.model.GenericFileProvider" on path: DexPathList[[zip file "/mnt/asec/com.polaris.testcloud-1/pkg.apk"],nativeLibraryDirectories=[/mnt/asec/com.polaris.testcloud-1/lib, /vendor/lib, /system/lib]]
                      at android.app.ActivityThread.installProvider(ActivityThread.java:5076)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:4647)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4584)
                      at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
                      at android.os.Handler.dispatchMessage(Handler.java:110)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:5357)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.netease.nim.uikit.common.media.model.GenericFileProvider" on path: DexPathList[[zip file "/mnt/asec/com.polaris.testcloud-1/pkg.apk"],nativeLibraryDirectories=[/mnt/asec/com.polaris.testcloud-1/lib, /vendor/lib, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                      at android.app.ActivityThread.installProvider(ActivityThread.java:5061)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:4647) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4584) 
                      at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403) 
                      at android.os.Handler.dispatchMessage(Handler.java:110) 
                      at android.os.Looper.loop(Looper.java:193) 
                      at android.app.ActivityThread.main(ActivityThread.java:5357) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by NicalDai** [comment]
估计是uikit用的glide版本和你们项目的不匹配
