### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 2263008 free bytes and 2209KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.

### ISSUE THREAD

**Issue by hangwangyu** [netease-kit/nim-uikit-android#70]
at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:54)
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:49)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:282)
	at sun.nio.cs.StreamEncoder.<init>(StreamEncoder.java:195)
	at sun.nio.cs.StreamEncoder.<init>(StreamEncoder.java:175)
	at sun.nio.cs.StreamEncoder.forOutputStreamWriter(StreamEncoder.java:59)
	at java.io.OutputStreamWriter.<init>(OutputStreamWriter.java:111)
	at java.io.FileWriter.<init>(FileWriter.java:78)
	at com.netease.nimlib.l.b.a.a.a(FileUtils.java:65)
	at com.netease.nimlib.l.b.d.a(NLogImpl.java:24)
	at com.netease.nimlib.l.b.a$3.run(LogBase.java:162)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Back traces ends.

**Comment by shine2008** [comment]
你好，请问什么场景下造成的？或者有更多的堆栈信息吗

**Comment by shine2008** [comment]
从堆栈上看，Failed to allocate a 8208 byte allocation只是申请一个8K的空间，对应的SDK代码是进行将一些缓存信息保存到本地，申请的使用的空间并不大，这个地方只是一个导火索，主要还是APP层面的内存占用要排查一下，在这个时候只剩下2M的内存空间了。当然，这个地方我们后续会继续优化，尽量更高效的使用内存
